# Generated by Django 5.2 on 2025-04-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('album', models.CharField(max_length=255)),
                ('duration_ms', models.IntegerField()),
                ('spotify_id', models.CharField(max_length=255, null=True, unique=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
