# Generated by Django 5.2 on 2025-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibelink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackplaylist',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
