# Generated by Django 5.2 on 2025-05-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vibelink", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("owner", models.CharField(max_length=100)),
                ("track_count", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="track",
            name="playlist_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
