# Generated by Django 5.2 on 2025-06-02 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vibelink", "0002_user_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackPlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vibelink.playlist",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vibelink.track"
                    ),
                ),
            ],
            options={
                "unique_together": {("track", "playlist")},
            },
        ),
    ]
