# Generated by Django 5.2 on 2025-05-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vibelink", "0002_playlist_track_playlist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="owner",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="spotify_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="artist",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="duration_ms",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="spotify_id",
            field=models.CharField(default="unknown", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
