# Generated by Django 5.2 on 2025-06-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibelink', '0002_trackplaylist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackplaylist',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='vibelink.track'),
        ),
    ]
