# Generated by Django 5.2 on 2025-06-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibelink', '0003_trackplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spotify_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
