# Generated by Django 5.2 on 2025-06-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibelink', '0003_alter_trackplaylist_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
