# Generated by Django 5.2 on 2025-06-12 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vibelink", "0004_track_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackrating",
            name="vibe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vibelink.vibe",
            ),
        ),
    ]
