# Generated by Django 5.2 on 2025-06-03 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibelink', '0005_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='algorithm',
            name='algorithm_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='callback',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='PlaylistSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibelink.playlist')),
            ],
            options={
                'unique_together': {('query', 'playlist')},
            },
        ),
        migrations.CreateModel(
            name='TrackCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibelink.algorithm')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibelink.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-coefficient'],
                'unique_together': {('track', 'algorithm', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TrackRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_rating', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Somewhat Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Somewhat Disagree'), (5, 'Strongly Disagree')])),
                ('purpose_rating', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Somewhat Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Somewhat Disagree'), (5, 'Strongly Disagree')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibelink.purpose')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibelink.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'track', 'purpose')},
            },
        ),
        migrations.CreateModel(
            name='TrackSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibelink.track')),
            ],
            options={
                'unique_together': {('query', 'track')},
            },
        ),
        migrations.CreateModel(
            name='UserXPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_users', to='vibelink.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'playlist')},
            },
        ),
        migrations.CreateModel(
            name='UserXTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_users', to='vibelink.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'track')},
            },
        ),
    ]
