# Generated by Django 5.2 on 2025-06-03 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibelink', '0006_purpose_algorithm_algorithm_type_algorithm_callback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserXAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_users', to='vibelink.algorithm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_algorithms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'algorithm')},
            },
        ),
    ]
