# Generated by Django 5.2 on 2025-06-03 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibelink', '0007_userxalgorithm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackcoefficient',
            old_name='algorithm',
            new_name='vibe',
        ),
        migrations.AlterUniqueTogether(
            name='trackcoefficient',
            unique_together={('track', 'vibe', 'user')},
        ),
        migrations.RenameModel(
            old_name='Algorithm',
            new_name='Vibe',
        ),
        migrations.CreateModel(
            name='UserVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vibes', to=settings.AUTH_USER_MODEL)),
                ('vibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibe_users', to='vibelink.vibe')),
            ],
            options={
                'unique_together': {('user', 'vibe')},
            },
        ),
        migrations.DeleteModel(
            name='UserXAlgorithm',
        ),
    ]
