# Generated by Django 5.2 on 2025-06-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibelink', '0008_rename_algorithm_trackcoefficient_vibe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibe',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
