# Generated by Django 5.2 on 2025-06-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibelink', '0009_alter_vibe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackrating',
            old_name='like_rating',
            new_name='rating',
        ),
        migrations.AlterUniqueTogether(
            name='trackrating',
            unique_together={('user', 'track')},
        ),
        migrations.RemoveField(
            model_name='trackrating',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='trackrating',
            name='purpose_rating',
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
